# Generated by Django 5.0.2 on 2024-03-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_editprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editprofile',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='editprofile',
            old_name='lastName',
            new_name='lastname',
        ),
    ]
