# Generated by Django 5.0.2 on 2024-03-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_firstname_editprofile_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editprofile',
            old_name='firstname',
            new_name='namefirst',
        ),
    ]
