# Generated by Django 4.2.6 on 2024-03-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_editprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofile',
            name='profileimage',
            field=models.ImageField(default='static/img/profile3.jpeg', upload_to='static/img/userimage/'),
        ),
    ]
