# Generated by Django 4.2.6 on 2024-03-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_editprofile_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofile',
            name='profileimage',
            field=models.ImageField(default='media/profile3.jpeg', upload_to='media/'),
        ),
    ]
