# Generated by Django 4.2.6 on 2024-03-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_editprofile_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofile',
            name='profileimage',
            field=models.ImageField(default='profile3.jpeg', upload_to='userimage/'),
        ),
    ]
