# Generated by Django 4.2.6 on 2024-03-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('fix_expense', models.IntegerField()),
                ('var_expense', models.IntegerField()),
                ('start_time', models.DateField(blank=True, null=True)),
                ('time', models.IntegerField()),
                ('totalexpense', models.IntegerField()),
                ('last_expense_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('goal_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('goalDeadline', models.DateField()),
                ('remainmonth', models.IntegerField()),
                ('remainyear', models.IntegerField()),
                ('remaindays', models.IntegerField()),
                ('start_time', models.DateField(blank=True, null=True)),
                ('time', models.IntegerField()),
                ('remainingamount', models.IntegerField()),
                ('days_in_month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('fix_salary', models.IntegerField()),
                ('var_salary', models.IntegerField()),
                ('start_time', models.DateField(blank=True, null=True)),
                ('time', models.IntegerField()),
                ('totalsalary', models.IntegerField()),
                ('last_salary_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
