# Generated by Django 5.0.2 on 2024-03-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0006_expense_user_goal_user_salary_sal_name_salary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
