# Generated by Django 5.0.2 on 2024-03-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0007_expense_start_time_salary_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='start_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
