# Generated by Django 5.0.2 on 2024-03-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0008_alter_salary_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
