<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-03-21 18:22
=======
# Generated by Django 4.2.6 on 2024-03-21 17:13
>>>>>>> 8036cabd0aead71d6d037c2ba38a0b01c9ebdf0c

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0009_alter_salary_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='start_time',
<<<<<<< HEAD
            field=models.IntegerField(blank=True, null=True),
=======
            field=models.IntegerField(default=0),
            preserve_default=False,
>>>>>>> 8036cabd0aead71d6d037c2ba38a0b01c9ebdf0c
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_time',
<<<<<<< HEAD
            field=models.IntegerField(blank=True, null=True),
=======
            field=models.IntegerField(),
>>>>>>> 8036cabd0aead71d6d037c2ba38a0b01c9ebdf0c
        ),
        migrations.AlterField(
            model_name='salary',
            name='start_time',
<<<<<<< HEAD
            field=models.IntegerField(blank=True, null=True),
=======
            field=models.IntegerField(),
>>>>>>> 8036cabd0aead71d6d037c2ba38a0b01c9ebdf0c
        ),
    ]
