# Generated by Django 5.0.2 on 2024-03-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0009_alter_salary_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='start_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='start_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
