# Generated by Django 5.0.2 on 2024-03-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0011_expense_time_goal_time_salary_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='time',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='time',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='time',
        ),
    ]
