# Generated by Django 5.0.2 on 2024-03-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0012_remove_expense_time_remove_goal_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
