# Generated by Django 5.0.2 on 2024-03-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0013_goal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='goalremaintime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
