# Generated by Django 5.0.2 on 2024-03-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0014_expense_time_goal_goalremaintime_salary_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='goalremaintime',
        ),
    ]
