# Generated by Django 5.0.2 on 2024-03-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0015_remove_goal_goalremaintime'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='remain',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
