# Generated by Django 5.0.2 on 2024-03-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0016_goal_remain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='remain',
            new_name='remainday',
        ),
        migrations.AddField(
            model_name='goal',
            name='remainmonth',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
