# Generated by Django 5.0.2 on 2024-03-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0017_rename_remain_goal_remainday_goal_remainmonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='remainday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='remainmonth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
