# Generated by Django 5.0.2 on 2024-03-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0018_alter_goal_remainday_alter_goal_remainmonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='remainday',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='remainmonth',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
