# Generated by Django 5.0.2 on 2024-03-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0019_alter_goal_remainday_alter_goal_remainmonth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='remainday',
            new_name='remainyear',
        ),
    ]
