# Generated by Django 5.0.2 on 2024-03-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0020_rename_remainday_goal_remainyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='remainday',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
