# Generated by Django 5.0.2 on 2024-03-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0021_goal_remainday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='remainday',
        ),
    ]
