# Generated by Django 5.0.2 on 2024-03-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0022_remove_goal_remainday'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='totalexpense',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='totalsalary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
