# Generated by Django 5.0.2 on 2024-03-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0023_expense_totalexpense_salary_totalsalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='firstexpfix',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='firstexpvar',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='firstgoal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='firstsalfix',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='firstsalvar',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
