# Generated by Django 5.0.2 on 2024-03-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0024_expense_firstexpfix_expense_firstexpvar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='firstgoal',
            new_name='firstgoalamount',
        ),
    ]
