# Generated by Django 5.0.2 on 2024-03-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0025_rename_firstgoal_goal_firstgoalamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='firstexpfix',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='firstexpvar',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='firstgoalamount',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='firstsalfix',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='firstsalvar',
        ),
    ]
