# Generated by Django 5.0.2 on 2024-03-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0026_remove_expense_firstexpfix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='last_salary_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
