# Generated by Django 5.0.2 on 2024-03-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0027_salary_last_salary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='last_expense_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
