# Generated by Django 5.0.2 on 2024-03-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0028_expense_last_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='remainingamount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
