# Generated by Django 5.0.2 on 2024-03-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0029_goal_remainingamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='remaindays',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
