# Generated by Django 5.0.2 on 2024-03-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0030_goal_remaindays'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='days_in_month',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
