# Generated by Django 4.2.6 on 2024-03-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0031_goal_days_in_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='exp_name',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='sal_name',
        ),
    ]
